"""update shopping carts for customer cart

Revision ID: 07ab6723b783
Revises: 9c4a1d2e8f32
Create Date: 2026-09-15 19:33:21.956545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07ab6723b783'
down_revision: Union[str, Sequence[str], None] = '9c4a1d2e8f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_reservation_items_status'), 'reservation_items', ['status'], unique=False)
    op.create_index('uq_shopping_cart_active_customer_branch', 'shopping_carts', ['customer_id', 'branch_id'], unique=True, postgresql_where=sa.text("status = 'ACTIVE'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_shopping_cart_active_customer_branch', table_name='shopping_carts', postgresql_where=sa.text("status = 'ACTIVE'"))
    op.drop_index(op.f('ix_reservation_items_status'), table_name='reservation_items')
    # ### end Alembic commands ###
