"""add inventory module

Revision ID: 2c16f62ab36f
Revises: 4fd4bd8c38ae
Create Date: 2026-08-30 10:27:34.679100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c16f62ab36f'
down_revision: Union[str, Sequence[str], None] = '4fd4bd8c38ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reserved_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('minimum_stock', sa.Integer(), server_default='0', nullable=False),
    sa.Column('maximum_stock', sa.Integer(), nullable=True),
    sa.Column('reorder_point', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('maximum_stock IS NULL OR maximum_stock >= minimum_stock', name='ck_inventory_maximum_stock_valid'),
    sa.CheckConstraint('minimum_stock >= 0', name='ck_inventory_minimum_stock_nonnegative'),
    sa.CheckConstraint('reorder_point >= 0', name='ck_inventory_reorder_point_nonnegative'),
    sa.CheckConstraint('reserved_quantity <= stock_quantity', name='ck_inventory_reserved_not_greater_than_stock'),
    sa.CheckConstraint('reserved_quantity >= 0', name='ck_inventory_reserved_quantity_nonnegative'),
    sa.CheckConstraint('stock_quantity >= 0', name='ck_inventory_stock_quantity_nonnegative'),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_id', 'product_variant_id', name='uq_inventory_branch_product_variant')
    )
    op.create_index(op.f('ix_inventories_branch_id'), 'inventories', ['branch_id'], unique=False)
    op.create_index(op.f('ix_inventories_id'), 'inventories', ['id'], unique=False)
    op.create_index(op.f('ix_inventories_is_active'), 'inventories', ['is_active'], unique=False)
    op.create_index(op.f('ix_inventories_product_variant_id'), 'inventories', ['product_variant_id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('stock_before', sa.Integer(), nullable=False),
    sa.Column('stock_after', sa.Integer(), nullable=False),
    sa.Column('reserved_before', sa.Integer(), server_default='0', nullable=False),
    sa.Column('reserved_after', sa.Integer(), server_default='0', nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('reference_code', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("\n            movement_type IN (\n                'ENTRY',\n                'SALE',\n                'ADJUSTMENT_IN',\n                'ADJUSTMENT_OUT',\n                'RETURN_IN',\n                'RETURN_OUT',\n                'RESERVE',\n                'RELEASE',\n                'TRANSFER_IN',\n                'TRANSFER_OUT'\n            )\n            ", name='ck_inventory_movement_type'),
    sa.CheckConstraint('quantity > 0', name='ck_inventory_movement_quantity_positive'),
    sa.CheckConstraint('reserved_after <= stock_after', name='ck_inventory_movement_reserved_after_valid'),
    sa.CheckConstraint('reserved_after >= 0', name='ck_inventory_movement_reserved_after_nonnegative'),
    sa.CheckConstraint('reserved_before <= stock_before', name='ck_inventory_movement_reserved_before_valid'),
    sa.CheckConstraint('reserved_before >= 0', name='ck_inventory_movement_reserved_before_nonnegative'),
    sa.CheckConstraint('stock_after >= 0', name='ck_inventory_movement_stock_after_nonnegative'),
    sa.CheckConstraint('stock_before >= 0', name='ck_inventory_movement_stock_before_nonnegative'),
    sa.CheckConstraint('unit_cost IS NULL OR unit_cost >= 0', name='ck_inventory_movement_unit_cost_nonnegative'),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_created_at'), 'inventory_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_movements_id'), 'inventory_movements', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_inventory_id'), 'inventory_movements', ['inventory_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_movement_type'), 'inventory_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_inventory_movements_reference_code'), 'inventory_movements', ['reference_code'], unique=False)
    op.create_index(op.f('ix_inventory_movements_reference_id'), 'inventory_movements', ['reference_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_reference_type'), 'inventory_movements', ['reference_type'], unique=False)
    op.create_index(op.f('ix_inventory_movements_supplier_id'), 'inventory_movements', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_user_id'), 'inventory_movements', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inventory_movements_user_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_supplier_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_reference_type'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_reference_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_reference_code'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_movement_type'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_inventory_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_created_at'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_inventories_product_variant_id'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_is_active'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_id'), table_name='inventories')
    op.drop_index(op.f('ix_inventories_branch_id'), table_name='inventories')
    op.drop_table('inventories')
    # ### end Alembic commands ###
