"""improve roles table

Revision ID: 3de1597e4cfb
Revises: 9be6e229278f
Create Date: 2026-08-23 12:13:32.082776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de1597e4cfb'
down_revision: Union[str, Sequence[str], None] = '9be6e229278f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('roles', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('roles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('roles_name_key'), 'roles', type_='unique')
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.create_unique_constraint(op.f('roles_name_key'), 'roles', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    op.drop_column('roles', 'is_active')
    op.drop_column('roles', 'description')
    # ### end Alembic commands ###
