"""add ready for pickup to orders

Revision ID: 43d73512294a
Revises: 6c5e415385df
Create Date: 2026-09-18 14:49:26.657758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43d73512294a'
down_revision: Union[str, Sequence[str], None] = '6c5e415385df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ready_for_pickup_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'ready_for_pickup_at')
    # ### end Alembic commands ###
