"""add supplier module

Revision ID: 4fd4bd8c38ae
Revises: 7802186aa073
Create Date: 2026-08-30 10:04:51.833377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fd4bd8c38ae'
down_revision: Union[str, Sequence[str], None] = '7802186aa073'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('business_name', sa.String(length=160), nullable=True),
    sa.Column('nit', sa.String(length=40), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_email'), 'suppliers', ['email'], unique=False)
    op.create_index(op.f('ix_suppliers_id'), 'suppliers', ['id'], unique=False)
    op.create_index(op.f('ix_suppliers_is_active'), 'suppliers', ['is_active'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_nit'), 'suppliers', ['nit'], unique=True)
    op.create_table('supplier_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('supplier_code', sa.String(length=80), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('minimum_order_quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('lead_time_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'product_id', name='uq_supplier_product'),
    sa.UniqueConstraint('supplier_id', 'supplier_code', name='uq_supplier_supplier_code')
    )
    op.create_index(op.f('ix_supplier_products_id'), 'supplier_products', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_products_is_active'), 'supplier_products', ['is_active'], unique=False)
    op.create_index(op.f('ix_supplier_products_product_id'), 'supplier_products', ['product_id'], unique=False)
    op.create_index(op.f('ix_supplier_products_supplier_id'), 'supplier_products', ['supplier_id'], unique=False)
    op.create_table('supplier_availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_product_id', sa.Integer(), nullable=False),
    sa.Column('product_variant_id', sa.Integer(), nullable=False),
    sa.Column('available_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='AVAILABLE', nullable=False),
    sa.Column('purchase_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('AVAILABLE', 'LOW_STOCK', 'OUT_OF_STOCK')", name='ck_supplier_availability_status'),
    sa.CheckConstraint('available_quantity >= 0', name='ck_supplier_availability_quantity_nonnegative'),
    sa.ForeignKeyConstraint(['product_variant_id'], ['product_variants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_product_id'], ['supplier_products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_product_id', 'product_variant_id', name='uq_supplier_product_variant_availability')
    )
    op.create_index(op.f('ix_supplier_availabilities_id'), 'supplier_availabilities', ['id'], unique=False)
    op.create_index(op.f('ix_supplier_availabilities_last_checked_at'), 'supplier_availabilities', ['last_checked_at'], unique=False)
    op.create_index(op.f('ix_supplier_availabilities_product_variant_id'), 'supplier_availabilities', ['product_variant_id'], unique=False)
    op.create_index(op.f('ix_supplier_availabilities_status'), 'supplier_availabilities', ['status'], unique=False)
    op.create_index(op.f('ix_supplier_availabilities_supplier_product_id'), 'supplier_availabilities', ['supplier_product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_availabilities_supplier_product_id'), table_name='supplier_availabilities')
    op.drop_index(op.f('ix_supplier_availabilities_status'), table_name='supplier_availabilities')
    op.drop_index(op.f('ix_supplier_availabilities_product_variant_id'), table_name='supplier_availabilities')
    op.drop_index(op.f('ix_supplier_availabilities_last_checked_at'), table_name='supplier_availabilities')
    op.drop_index(op.f('ix_supplier_availabilities_id'), table_name='supplier_availabilities')
    op.drop_table('supplier_availabilities')
    op.drop_index(op.f('ix_supplier_products_supplier_id'), table_name='supplier_products')
    op.drop_index(op.f('ix_supplier_products_product_id'), table_name='supplier_products')
    op.drop_index(op.f('ix_supplier_products_is_active'), table_name='supplier_products')
    op.drop_index(op.f('ix_supplier_products_id'), table_name='supplier_products')
    op.drop_table('supplier_products')
    op.drop_index(op.f('ix_suppliers_nit'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_is_active'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_id'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_email'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
