"""update employee branch history constraint

Revision ID: 6a5b6c86cfc1
Revises: 44f413ac9430
Create Date: 2026-09-03 19:13:43.382486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5b6c86cfc1'
down_revision: Union[str, Sequence[str], None] = '44f413ac9430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_employee_branch_active'), 'employee_branches', type_='unique')
    op.create_index('uq_employee_one_active_branch', 'employee_branches', ['user_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_employee_one_active_branch', table_name='employee_branches', postgresql_where=sa.text('is_active = true'))
    op.create_unique_constraint(op.f('uq_employee_branch_active'), 'employee_branches', ['user_id', 'branch_id', 'is_active'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
