"""update order payment flow

Revision ID: 6c5e415385df
Revises: 07ab6723b783
Create Date: 2026-09-17 13:23:54.207752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c5e415385df'
down_revision: Union[str, Sequence[str], None] = '07ab6723b783'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_type', sa.String(length=20), server_default='PICKUP', nullable=False))
    op.add_column('orders', sa.Column('shipping_address', sa.String(length=500), nullable=True))
    op.add_column('orders', sa.Column('tracking_code', sa.String(length=120), nullable=True))
    op.add_column('orders', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_orders_tracking_code'), 'orders', ['tracking_code'], unique=False)
    op.create_check_constraint('ck_order_delivery_type', 'orders', "delivery_type IN ('PICKUP', 'DELIVERY')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_order_delivery_type', 'orders', type_='check')
    op.drop_index(op.f('ix_orders_tracking_code'), table_name='orders')
    op.drop_column('orders', 'cancelled_at')
    op.drop_column('orders', 'completed_at')
    op.drop_column('orders', 'delivered_at')
    op.drop_column('orders', 'shipped_at')
    op.drop_column('orders', 'paid_at')
    op.drop_column('orders', 'tracking_code')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'delivery_type')
    # ### end Alembic commands ###
