"""add cloudinary public ids

Revision ID: b2ef66633391
Revises: 6a5b6c86cfc1
Create Date: 2026-09-04 17:13:15.637174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2ef66633391'
down_revision: Union[str, Sequence[str], None] = '6a5b6c86cfc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product_images', sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True))
    op.add_column('product_variants', sa.Column('cloudinary_public_id', sa.String(length=255), nullable=True))
    op.add_column('products', sa.Column('cover_image_public_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'cover_image_public_id')
    op.drop_column('product_variants', 'cloudinary_public_id')
    op.drop_column('product_images', 'cloudinary_public_id')
    # ### end Alembic commands ###
