"""add birth date and profile completed

Revision ID: bf522e955c55
Revises: d813d4cf047f
Create Date: 2026-08-23 12:39:56.057739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf522e955c55'
down_revision: Union[str, Sequence[str], None] = 'd813d4cf047f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('profile_completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_completed')
    op.drop_column('users', 'date_of_birth')
    # ### end Alembic commands ###
