"""add product images and virtual fitting assets

Revision ID: f9fbb28ff9c9
Revises: 9d16044e887e
Create Date: 2026-08-29 16:46:33.850276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9fbb28ff9c9'
down_revision: Union[str, Sequence[str], None] = '9d16044e887e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.create_index(op.f('ix_product_images_product_id'), 'product_images', ['product_id'], unique=False)
    op.create_table('virtual_fitting_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('asset_url', sa.String(length=500), nullable=False),
    sa.Column('asset_type', sa.String(length=30), nullable=False),
    sa.Column('garment_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['color_id'], ['colors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_fitting_assets_color_id'), 'virtual_fitting_assets', ['color_id'], unique=False)
    op.create_index(op.f('ix_virtual_fitting_assets_id'), 'virtual_fitting_assets', ['id'], unique=False)
    op.create_index(op.f('ix_virtual_fitting_assets_product_id'), 'virtual_fitting_assets', ['product_id'], unique=False)
    op.add_column('products', sa.Column('cover_image_url', sa.String(length=500), nullable=True))
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('products', 'cover_image_url')
    op.drop_index(op.f('ix_virtual_fitting_assets_product_id'), table_name='virtual_fitting_assets')
    op.drop_index(op.f('ix_virtual_fitting_assets_id'), table_name='virtual_fitting_assets')
    op.drop_index(op.f('ix_virtual_fitting_assets_color_id'), table_name='virtual_fitting_assets')
    op.drop_table('virtual_fitting_assets')
    op.drop_index(op.f('ix_product_images_product_id'), table_name='product_images')
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.drop_table('product_images')
    # ### end Alembic commands ###
